# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:      Booth Group
# tagline:          "Website for the Research Group of George Booth at King's College London for Computational Electronic Structure"
description:      "Research Group at King's College London for Computational Electronic Structure"
url:              ''
baseurl:          /

author:
  name:           'George Booth'
  email:          george.booth24@gmail.com
  github_username: ghb24

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
